Large Langage Models (LLM) are type of generative AI that specializes in generating coherent responses to input text.
N.B : LLM is considered as Deep Learning based upon massive corpus of text. 
It can be used for a wide range of natural langage processing task.
Example --> LLM allows us to have specialized chatbot 
How it works :
LLMs takes an input text (known as prompt) and break the input into sequence of numerical tokens (tokenization), the model then uses a probability distribution to predict the next token and repeat the same method for each token.
N.B : transformers is Hugging Face's library that provide an space to use LLM/NLP model ; pytorch is a deep learning's framework

In [0]:
pip install transformers torch

Collecting transformers
  Downloading transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
Collecting torch
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_aarch64.whl.metadata (30 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.18.0)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers)
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /databricks/python3/lib/python3.12/site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /databricks/python3/lib/python3.12/site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /databricks/python3/lib/python3.12/site-packages (from transformers) (6.0.2)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2025.11.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl.metadata (40 kB)
Requirement already satisfied: requests in /databricks/python3/lib/python3.12/site-packages (from transformers) (2.32.3)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.8 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (4.1 kB)
Collecting tqdm>=4.27 (from transformers)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in /databricks/python3/lib/python3.12/site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (74.0.0)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Downloading networkx-3.6-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in /databricks/python3/lib/python3.12/site-packages (from torch) (3.1.5)
Requirement already satisfied: fsspec>=0.8.5 in /databricks/python3/lib/python3.12/site-packages (from torch) (2023.5.0)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.34.0->transformers)
  Downloading hf_xet-1.2.0-cp37-abi3-manylinux_2_28_aarch64.whl.metadata (4.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /databricks/python3/lib/python3.12/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.12/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.12/site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /databricks/python3/lib/python3.12/site-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.12/site-packages (from requests->transformers) (2025.1.31)
Downloading transformers-4.57.3-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 70.7 MB/s eta 0:00:00
Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_aarch64.whl (104.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 MB 106.4 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.0-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.1/566.1 kB 7.7 MB/s eta 0:00:00
Downloading networkx-3.6-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 84.0 MB/s eta 0:00:00
Downloading regex-2025.11.3-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl (798 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.6/798.6 kB 9.4 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (491 kB)
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 88.0 MB/s eta 0:00:00
Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 112.9 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading hf_xet-1.2.0-cp37-abi3-manylinux_2_28_aarch64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 81.5 MB/s eta 0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 20.1 MB/s eta 0:00:00
Installing collected packages: mpmath, tqdm, sympy, safetensors, regex, networkx, hf-xet, torch, huggingface-hub, tokenizers, transformers
Successfully installed hf-xet-1.2.0 huggingface-hub-0.36.0 mpmath-1.3.0 networkx-3.6 regex-2025.11.3 safetensors-0.7.0 sympy-1.14.0 tokenizers-0.22.1 torch-2.9.1 tqdm-4.67.1 transformers-4.57.3
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
from huggingface_hub import login
login(token="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")

In [0]:
pip install accelerate

Collecting accelerate
  Downloading accelerate-1.12.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in /databricks/python3/lib/python3.12/site-packages (from accelerate) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /databricks/python3/lib/python3.12/site-packages (from accelerate) (24.1)
Requirement already satisfied: psutil in /databricks/python3/lib/python3.12/site-packages (from accelerate) (5.9.0)
Requirement already satisfied: pyyaml in /databricks/python3/lib/python3.12/site-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-dd297bf2-f450-47cb-903f-410f36d8391e/lib/python3.12/site-packages (from accelerate) (2.9.1)
Requirement already satisfied: huggingface_hub>=0.21.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-dd297bf2-f450-47cb-903f-410f36d8391e/lib/python3.12/site-packages (from accelerate) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-dd297bf2-f450-47cb-903f-410f36d8391e/lib/python3.12/site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /databricks/python3/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (2023.5.0)
Requirement already satisfied: requests in /databricks/python3/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-dd297bf2-f450-47cb-903f-410f36d8391e/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /databricks/python3/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.12.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-dd297bf2-f450-47cb-903f-410f36d8391e/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (74.0.0)
Requirement already satisfied: sympy>=1.13.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-dd297bf2-f450-47cb-903f-410f36d8391e/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-dd297bf2-f450-47cb-903f-410f36d8391e/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.6)
Requirement already satisfied: jinja2 in /databricks/python3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-dd297bf2-f450-47cb-903f-410f36d8391e/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /databricks/python3/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.12/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.12/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /databricks/python3/lib/python3.12/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.12/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2025.1.31)
Downloading accelerate-1.12.0-py3-none-any.whl (380 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.12.0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
# First example of LLM usage
# We will use the Mistral 7B model

from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL = "mistralai/Mistral-7B-Instruct-v0.2"

tokenizer = AutoTokenizer.from_pretrained(MODEL)

model = AutoModelForCausalLM.from_pretrained(
    MODEL,
    device_map="auto",
    torch_dtype="auto"
)

prompt = "Explique en termes simples ce qu'est l'intelligence artificielle :"

# Break the prompt into a sequence of numerical tokens 
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

# Creation of the response to the initial prompt
# The outputs will take the prompt (tokenized) and ask the model (mistral7b) to generate an accurate and creative response

outputs = model.generate(
    **inputs,
    max_new_tokens=200,
    temperature=0.7,
    top_p=0.9
)

# Displaying the response to our prompt
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Some parameters are on the meta device because they were offloaded to the disk and cpu.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Explique en termes simples ce qu'est l'intelligence artificielle :

Intelligence artificielle (IA) est un type de technologie informatique qui permet à des ordinateurs ou des robots de penser et d'agir comme les humains. Cela signifie qu'ils peuvent comprendre des informations, raisonner et apprendre à résoudre des problèmes. Par exemple, une IA peut analyser des données pour détecter des tendances, parler comme une personne grâce à l'intelligence de langage naturel, ou jouer aux échecs à un niveau très élevé. Elle peut également être utilisée pour automatiser des tâches répétitives, gérer des systèmes complexes ou prendre des décisions basées sur des données. En général, l'IA vise à créer des systèmes intelligents qui peuvent interagir avec le monde réel et rés

In [0]:
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Here we take the FLAN-T5 base model

MODEL = "google/flan-t5-base"
device = "mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu")

# 1st step : take the input (a prompt)
tokenizer = AutoTokenizer.from_pretrained(MODEL)

# This step will take the original prompt into the model
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL).to(device)
 
prompt = "Explique en termes simples ce qu'est l'intelligence artificielle :"

# break the input into sequence of numerical tokens (tokenization)
inputs = tokenizer(prompt, return_tensors="pt").to(device)

# the model then uses a probability distribution to predict the next token and repeat the same method for each token
outputs = model.generate(**inputs, max_new_tokens=150)

# Displaying the response to our prompt
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Simplely expresses what it is artistic intelligence:

In [0]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL = "facebook/opt-350m"


device = "mps" if torch.backends.mps.is_available() else "cpu"
print("Using device:", device)

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL)

model = AutoModelForCausalLM.from_pretrained(
    MODEL,
    dtype=torch.float16  # utiliser dtype au lieu de torch_dtype
).to(device)

# Prompt
prompt = "Explique en termes simples la différence entre le machine learning supervisé et non supervisé."
inputs = tokenizer(prompt, return_tensors="pt").to(device)

# Generation of the optimized response
outputs = model.generate(
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],
    max_new_tokens=150,
    temperature=0.7,
    top_p=0.9,
    do_sample=True
)

# Displaying the response to our prompt
print(tokenizer.decode(outputs[0], skip_special_tokens=True, clean_up_tokenization_spaces=True))

Using device: cpu

tokenizer_config.json:   0%|          | 0.00/685 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/644 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/441 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/663M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/662M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

Explique en termes simples la différence entre le machine learning supervisé et non supervisé.

Un machine learning supervisé est un technique à un moment où elle est dans un mode de sécurité. Dans un cas, elle est plus dangereux que le nombre d'intérêts en sécurité, ou l'écart de sécurité, ou la réalisation des pratiques de sécurité.

Au cours des dernières semaines, leur technique est en vigueur dans le cas d'un machine learning supervisé, avec une réalisation de sécurité.

Le nombre d'intérêts en

Here, we will use an LLM model that enables us to understand our prompt, which is useful for classifying prompts into categories. For example, this use of LLM can be used to collect customer reviews on a product for sale in order to measure customer satisfaction. In general, text classification is used to organize, understand, prioritize, and automate all types of text flows.

In [0]:
# BERT is bidirectional and widely used for comprehension tasks (not generation).
# For comprehension, classification, extraction

from transformers import pipeline

# BERT fine-tuned for sentiment classification
classifier = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

texte = "J'adore ce film, il est incroyable !"
result = classifier(texte)
print(result)

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cpu

[{'label': '5 stars', 'score': 0.8262948393821716}]

Our model: nlptown/bert-base-multilingual-uncased-sentiment
Our model has been trained to classify the sentiment of sentences on a scale of 1 to 5 stars.
1 star = very negative
2 stars = negative
3 stars = neutral/average
4 stars = positive
5 stars = very positive

In [0]:
# T5 is an encoder-decoder (seq2seq) model, perfect for translation, summarization, and Q&A.
# For text transformation (summarization, translation, Q&A).

from transformers import pipeline

# Load a T5 model that has already been fine-tuned for summarization
summarizer = pipeline("summarization", model="t5-small")

# Example text

texte = """
L'intelligence artificielle (IA) désigne l'ensemble des théories et des techniques développant
des programmes informatiques capables de simuler des traits de l'intelligence humaine tels que
le raisonnement, l'apprentissage, la planification ou encore la créativité.
"""

res = summarizer(
    texte,
    max_new_tokens=60,   # maximum length of the generated summary
    min_length=20,       # summary of at least 20
    do_sample=False      # deterministic generation
)

print("Résumé :", res)

# The summary of our prompt will be very similar to our initial prompt because the latter is not very long
# The idea here is to understand how rapid synthesis works and how to implement an LLM for this purpose.

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

Device set to use cpu
Your max_length is set to 200, but your input_length is only 69. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=34)

Résumé : [{'summary_text': "L'intelligence artificielle désigne l'ensemble des théories et des techniques développant des programmes informatiques capables de simuler des traits tels que le raisonnement, l’apprentissage, la planification ou encore la créativité."}]

In [0]:
# Same model in a more interpretable form for possible presentations to teams unfamiliar with LLM methods 

from transformers import pipeline

# Loading the pipeline
classifier = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

# Correspondence dictionary
sentiment_map = {
    "1 star": "Très négatif",
    "2 stars": "Négatif",
    "3 stars": "Neutre",
    "4 stars": "Positif",
    "5 stars": "Très positif"
}

def analyze_sentiment(text):
    result = classifier(text)[0]
    label = result['label']
    score = result['score']
    sentiment = sentiment_map.get(label, label)
    return {"sentiment": sentiment, "score": round(score, 3)}

# Tests
print(analyze_sentiment("J'adore ce film, il est incroyable !"))
print(analyze_sentiment("C'est correct, sans plus."))
print(analyze_sentiment("Je déteste ce produit, il est nul !"))

Device set to use cpu

{'sentiment': 'Très positif', 'score': 0.826}
{'sentiment': 'Neutre', 'score': 0.76}
{'sentiment': 'Très négatif', 'score': 0.941}

Practical application of LLM principles for sentiment classification on a dataset

In [0]:
import pandas as pd

data = pd.read_csv(
    'product_reviews.csv',
    on_bad_lines='skip',
    sep=';'
)

display(data)

text,product_category,Unnamed: 2,Unnamed: 3,Unnamed: 4
Thanks for the product. It was exactly as described and exactly what I was looking for. Great quality and I look forward to ordering more in the future.,Cell Phones and Accessories,null,null,null
"I saw him almost win the American Idol on whichever year it was. I have watched him on different shows and read about him on the entertainment pages. Yes he is a little out there sometimes, but he can sing!",Digital Music,null,null,null
"Very good quality filament. Surface texture is as expected, feeds well and extrudes well. I'm buying more. Recommend it. Bruce",Industrial and Scientific,null,null,null
I have tried the cheaper carts and they do not do well. These are priced lower than most and they work well.,Office Products,null,null,null
"I purchased this to sit on a shelf of a floor lamp, to complete my Tiki/Pirate/Polynesian/Asian themed décor, and it does exactly what I had hoped it would do. The photo DOES NOT do justice to the floor lamp...it really is beautiful, as well.",Toys and Games,null,null,null
Truck shell was cracked upon arrival The suspension arms of the terremoto seem to have way to much play in them ... shock towers amd other seemingly weak points. Straight drivin becomes even more challenging at speed. it seems like it can take a beating but i would not get carried away. Ran through some water no issues Light bashing so far no issues,Toys and Games,null,null,null
Not bad but super not durable! After only a couple days the strap broke and the only thing really good about it is that it does protect the phone.,Cell Phones and Accessories,null,null,null
These are basically crap..... Not ONE of them actually CHARGES my phone or tablet... Unless it's overnight..... My phone dies while plugged in if I'm doing ANYTHING on my phone while it charges with these.... Definately do NOT recommend,Cell Phones and Accessories,null,null,null
"Synth beats, smoking weed, beetches, sampling. I was hoping to find something new and intriguing but I found the same old same old. Not trying to hate, but I was disappointed. Dude can flow, but the message is the same.",Digital Music,null,null,null
like all the versions - but be careful - not for young ears...there are some 'bad words' and 'terms' they should not hear but cute for adults.,Digital Music,null,null,null
"A nice alternative to spending more money at the Verizon or Apple store, and it works exactly the same, so I'm sold!",Electronics,null,null,null
With the constant changes in connections this little item made the transition to my dual monitor system much easier. The price was extremely good and the quality of the adapter was great.,Electronics,null,null,null
excellent product. I especially like the feature of being able to charge from a separate power source; like a computer. the feature of the port for charging other items from this fan is unique.,Electronics,null,null,null
The magnetic attachment is much more convenient than attempting to hook the tag over the mirror. This is especially important since the new tags are made from thinner material and tend to be rather limp.,Industrial and Scientific,null,null,null
I bought these bearings as replacements for the ones supplied with my 3D printer kit as they made a lot of noise. I've replaced those on my Y axis and there is absolutely no noise now! I read reviews elsewhere that recommenced these and now I too can recommend them! They fit my mounts perfectly and slid effortlessly.,Industrial and Scientific,null,null,null
I make sure I have one of these at every job I go to. This is super comfortable and supportive and it's big enough that I don't run out of space on the mouse pad.,Office Products,null,null,null
this is perfect for what i needed! its thin cork on top of cardboard. but HONESTLY it works just fine and i have had NO issues. it gets heavy use in my place. and is doing just fine!,Office Products,null,null,null
"just what we expected to protect our computer and it has done a good job so far, nothing fancy and we still have some minor problems with junk that needs cleaning, maybe from norton",Software,null,null,null
"Don't know know I ever got by without it. 10 plus years, but wish I could have stuck with older version, I really don't need all the other bells and whistles that come with it. I had to upgrade so I could download credit card charges",Software,null,null,null
I wasn't a fan of the ribbon when MS first introduced that. I think they've fixed some of the things that still bothered me with this version. If I could just get them to upgrade to this at work I'd be set!!,Software,null,null,null
I was very disappointed in this. The elephant plays a song. Not sure why it doesn't make elephant noises but they could have done so much more with these bigger animals.,Toys and Games,null,null,null

In [0]:
data.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'], axis=1, inplace=True)
data.head()

                                                text             product_category
0  Thanks for the product. It was exactly as desc...  Cell Phones and Accessories
1  I saw him almost win the American Idol on whic...                Digital Music
2  Very good quality filament. Surface texture is...    Industrial and Scientific
3  I have tried the cheaper carts and they do not...              Office Products
4  I purchased this to sit on a shelf of a floor ...               Toys and Games

In [0]:
from transformers import pipeline

# BERT fine-tuned for sentiment classification
classifier = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

texte = data['text']
results = []
def prediction (text):
    for texte in data['text']:
        result = classifier(texte)
        results.append(result)
    #print(result)
    #print(texte)
data['prediction'] = data['text'].apply(prediction)
data.head()

Device set to use cpu

                                                text  ... prediction
0  Thanks for the product. It was exactly as desc...  ...       None
1  I saw him almost win the American Idol on whic...  ...       None
2  Very good quality filament. Surface texture is...  ...       None
3  I have tried the cheaper carts and they do not...  ...       None
4  I purchased this to sit on a shelf of a floor ...  ...       None

[5 rows x 3 columns]

In [0]:
# Algorithm for summarizing a prompt 

import pandas as pd
from transformers import pipeline

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")  # modèle open-access

# Function to summarize a text
def summarize_text(text, max_length=None):
    #  Automatic adjustment of max_length if necessary
    if max_length is None:
        input_len = len(text.split())
        max_length = max(10, min(50, input_len // 2))
    
    summary = summarizer(text, max_length=max_length, min_length=5, do_sample=False)
    return summary[0]["summary_text"]

# Apply to the column
data["resume"] = data["text"].apply(summarize_text)
data

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

                                                 text  ...                                             resume
0   Thanks for the product. It was exactly as desc...  ...  Great quality and I look forward to ordering m...
1   I saw him almost win the American Idol on whic...  ...  I saw him almost win the American Idol on whic...
2   Very good quality filament. Surface texture is...  ...        Very good quality filament. Surface texture
3   I have tried the cheaper carts and they do not...  ...          These are priced lower than most and they
4   I purchased this to sit on a shelf of a floor ...  ...  "I purchased this to sit on a shelf of a floor...
5   Truck shell was cracked upon arrival\nThe susp...  ...  The suspension arms of the terremoto seem to h...
6   Not bad but super not durable! After only a co...  ...  After only a couple days the strap broke and t...
7   These are basically crap..... Not ONE of them ...  ...  Not ONE of them actually CHARGES my phone or t...
8   Synth beats, smoking weed, beetches, sampling....  ...  "I was hoping to find something new and intrig...
9   like all the versions - but be careful - not f...  ...              There are some 'bad words' and 'terms
10  A nice alternative to spending more money at t...  ...       A nice alternative to spending more money at
11  With the constant changes in connections this ...  ...  The price was extremely good and the quality o...
12  excellent product.  I especially like the feat...  ...  I especially like the feature of being able to...
13  The magnetic attachment is much more convenien...  ...  The magnetic attachment is much more convenien...
14  I bought these bearings as replacements for th...  ...  I bought these bearings as replacements for th...
15  I make sure I have one of these at every job I...  ...  "I make sure I have one of these at every job ...
16  this is perfect for what i needed! its thin co...  ...  This is perfect for what i needed! its thin co...
17  just what we expected to protect our computer ...  ...  "It has done a good job so far, nothing fancy ...
18  Don't know know I ever got by without it. 10 p...  ...  "I really don't need all the other bells and w...
19  I wasn't a fan of the ribbon when MS first int...  ...  I wasn't a fan of the ribbon when MS first int...
20  I was very disappointed in this.  The elephant...  ...  I was very disappointed in this. The elephant ...

[21 rows x 4 columns]

In [0]:
def predict_sentiment(text):
    result = classifier(text)[0]  
    return result['label']
data['prediction'] = data['text'].apply(predict_sentiment)
data

                                                 text  ...                                             resume
0   Thanks for the product. It was exactly as desc...  ...  Great quality and I look forward to ordering m...
1   I saw him almost win the American Idol on whic...  ...  I saw him almost win the American Idol on whic...
2   Very good quality filament. Surface texture is...  ...        Very good quality filament. Surface texture
3   I have tried the cheaper carts and they do not...  ...          These are priced lower than most and they
4   I purchased this to sit on a shelf of a floor ...  ...  "I purchased this to sit on a shelf of a floor...
5   Truck shell was cracked upon arrival\nThe susp...  ...  The suspension arms of the terremoto seem to h...
6   Not bad but super not durable! After only a co...  ...  After only a couple days the strap broke and t...
7   These are basically crap..... Not ONE of them ...  ...  Not ONE of them actually CHARGES my phone or t...
8   Synth beats, smoking weed, beetches, sampling....  ...  "I was hoping to find something new and intrig...
9   like all the versions - but be careful - not f...  ...              There are some 'bad words' and 'terms
10  A nice alternative to spending more money at t...  ...       A nice alternative to spending more money at
11  With the constant changes in connections this ...  ...  The price was extremely good and the quality o...
12  excellent product.  I especially like the feat...  ...  I especially like the feature of being able to...
13  The magnetic attachment is much more convenien...  ...  The magnetic attachment is much more convenien...
14  I bought these bearings as replacements for th...  ...  I bought these bearings as replacements for th...
15  I make sure I have one of these at every job I...  ...  "I make sure I have one of these at every job ...
16  this is perfect for what i needed! its thin co...  ...  This is perfect for what i needed! its thin co...
17  just what we expected to protect our computer ...  ...  "It has done a good job so far, nothing fancy ...
18  Don't know know I ever got by without it. 10 p...  ...  "I really don't need all the other bells and w...
19  I wasn't a fan of the ribbon when MS first int...  ...  I wasn't a fan of the ribbon when MS first int...
20  I was very disappointed in this.  The elephant...  ...  I was very disappointed in this. The elephant ...

[21 rows x 4 columns]

In [0]:
# Addition of a column for improved interpretability 
def libelle(text):
    if text == '1 star':
        return 'Très mauvais'
    elif text == '2 stars':
        return 'Mauvais'
    elif text == '3 stars':
        return 'Neutre'
    elif text == '4 stars':
        return 'Bon'
    else:
        return 'Très bon'
data['Libellé']=data['prediction'].apply(libelle)
data

                                                 text  ...       Libellé
0   Thanks for the product. It was exactly as desc...  ...      Très bon
1   I saw him almost win the American Idol on whic...  ...           Bon
2   Very good quality filament. Surface texture is...  ...      Très bon
3   I have tried the cheaper carts and they do not...  ...        Neutre
4   I purchased this to sit on a shelf of a floor ...  ...      Très bon
5   Truck shell was cracked upon arrival\nThe susp...  ...       Mauvais
6   Not bad but super not durable! After only a co...  ...        Neutre
7   These are basically crap..... Not ONE of them ...  ...  Très mauvais
8   Synth beats, smoking weed, beetches, sampling....  ...       Mauvais
9   like all the versions - but be careful - not f...  ...        Neutre
10  A nice alternative to spending more money at t...  ...           Bon
11  With the constant changes in connections this ...  ...      Très bon
12  excellent product.  I especially like the feat...  ...      Très bon
13  The magnetic attachment is much more convenien...  ...      Très bon
14  I bought these bearings as replacements for th...  ...      Très bon
15  I make sure I have one of these at every job I...  ...      Très bon
16  this is perfect for what i needed! its thin co...  ...      Très bon
17  just what we expected to protect our computer ...  ...           Bon
18  Don't know know I ever got by without it. 10 p...  ...        Neutre
19  I wasn't a fan of the ribbon when MS first int...  ...           Bon
20  I was very disappointed in this.  The elephant...  ...       Mauvais

[21 rows x 5 columns]